language: python
python:
  - "3.7"

install:
  - pip install -r requirements-test.txt
  - pip install coveralls
  - pip install .

script: nosetests -v --with-coverage --cover-package=pyjsonrpc
after_success: coveralls $COVERALLS_OPTION
